server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 7cf55ebe-8005-4c48-a506-36b219d8ae62
          #        test
        cluster-name: ZJ
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: user-center
#          uri: lb://user-center
#          predicates:
#            - Path= /user-center/**
#          filters:
#            - StripPrefix=1

management:
  endpoints:
    web:d
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.wistron: debug